#!/usr/bin/env python3
"""Embed sidebar templates and the fixture so packaged builds have no runtime data-file dependency."""
import json
from pathlib import Path
root = Path(__file__).resolve().parents[1]
out = root / 'src/uishell/generated/sidebar_fixture.h'
text = '// Generated by tools/embed-sidebar-fixture.py.\n'
for name, file in [('fixture_config', 'fixture.kdl'), ('fixture_patches', 'fixture.jsonl'), ('local_config', 'local.kdl')]:
    text += f'static const char uishell_sidebar_{name}[] =\n'
    text += '\n'.join(json.dumps(line, ensure_ascii=True) for line in (root / 'data/sidebar' / file).read_text().splitlines(keepends=True)) + ';\n'
resources = json.loads((root / 'data/sidebar/resources.json').read_text())
text += 'static const UIShell_SidebarResource uishell_sidebar_fixture_resources[] = {\n'
for resource in resources:
    text += '  {' + ', '.join(json.dumps(resource[key]) for key in ['id', 'label', 'command', 'windows_command']) + '},\n'
text += '};\n'
if not out.exists() or out.read_text() != text:
    out.write_text(text)
